apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: accounts-db
spec:
  template:
    spec:
      serviceAccountName: $KSA_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancereader
spec:
  template:
    spec:
      serviceAccountName: $KSA_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
spec:
  template:
    spec:
      serviceAccountName: $KSA_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      serviceAccountName: $KSA_NAME
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ledger-db
spec:
  template:
    spec:
      serviceAccountName: $KSA_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerwriter
spec:
  template:
    spec:
      serviceAccountName: $KSA_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  template:
    spec:
      serviceAccountName: $KSA_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionhistory
spec:
  template:
    spec:
      serviceAccountName: $KSA_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  template:
    spec:
      serviceAccountName: $KSA_NAME
